steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/election-iq', 
    '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY',
    '--build-arg', 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY',
    '.'
  ]
images:
- 'gcr.io/$PROJECT_ID/election-iq'
timeout: '1200s'
